<?php
/**
 * Default manifest file
 *
 * @var array
 */
$settings = array(
	'xml' => false,
	'advanced_import' => array(
		'default' => array(
			'label'    => esc_html__( 'Default', 'monstroid2' ),
			'full'     => get_template_directory() . '/assets/demo-content/default/default-full.xml',
			'lite'     => get_template_directory() . '/assets/demo-content/default/default-min.xml',
			'thumb'    => get_template_directory_uri() . '/assets/demo-content/default/default-thumb.png',
			'demo_url' => 'https://ld-wp.template-help.com/wordpress_62222_default/',
		),
		'skin-1' => array(
			'label'    => esc_html__( 'Construction', 'monstroid2' ),
			'full'     => get_template_directory() . '/assets/demo-content/skin-1/skin-1-full.xml',
			'lite'     => get_template_directory() . '/assets/demo-content/skin-1/skin-1-min.xml',
			'thumb'    => get_template_directory_uri() . '/assets/demo-content/skin-1/skin-1-thumb.png',
			'demo_url' => 'https://ld-wp.template-help.com/wordpress_62222_construction/',
		),
		'skin-2' => array(
			'label'    => esc_html__( 'Fashion', 'monstroid2' ),
			'full'     => get_template_directory() . '/assets/demo-content/skin-2/skin-2-full.xml',
			'lite'     => get_template_directory() . '/assets/demo-content/skin-2/skin-2-min.xml',
			'thumb'    => get_template_directory_uri() . '/assets/demo-content/skin-2/skin-2-thumb.png',
			'demo_url' => 'https://ld-wp.template-help.com/wordpress_62222_fashion/',
		),
		'skin-3' => array(
			'label'    => esc_html__( 'Corporate', 'monstroid2' ),
			'full'     => get_template_directory() . '/assets/demo-content/skin-3/skin-3-full.xml',
			'lite'     => get_template_directory() . '/assets/demo-content/skin-3/skin-3-min.xml',
			'thumb'    => get_template_directory_uri() . '/assets/demo-content/skin-3/skin-3-thumb.png',
			'demo_url' => 'https://ld-wp.template-help.com/wordpress_62222_corporate/',
		),
		'skin-4' => array(
			'label'    => esc_html__( 'Furni', 'monstroid2' ),
			'full'     => get_template_directory() . '/assets/demo-content/skin-4/skin-4-full.xml',
			'lite'     => get_template_directory() . '/assets/demo-content/skin-4/skin-4-min.xml',
			'thumb'    => get_template_directory_uri() . '/assets/demo-content/skin-4/skin-4-thumb.png',
			'demo_url' => 'https://ld-wp.template-help.com/wordpress_62222_furni/',
		),
		'skin-5' => array(
			'label'    => esc_html__( 'Ironmass', 'monstroid2' ),
			'full'     => get_template_directory() . '/assets/demo-content/skin-5/skin-5-full.xml',
			'lite'     => get_template_directory() . '/assets/demo-content/skin-5/skin-5-min.xml',
			'thumb'    => get_template_directory_uri() . '/assets/demo-content/skin-5/skin-5-thumb.png',
			'demo_url' => 'https://ld-wp.template-help.com/wordpress_62222_ironmass_v1/',
		),
		'skin-6' => array(
			'label'    => esc_html__( 'Lawyer', 'monstroid2' ),
			'full'     => get_template_directory() . '/assets/demo-content/skin-6/skin-6-full.xml',
			'lite'     => get_template_directory() . '/assets/demo-content/skin-6/skin-6-min.xml',
			'thumb'    => get_template_directory_uri() . '/assets/demo-content/skin-6/skin-6-thumb.png',
			'demo_url' => 'https://ld-wp.template-help.com/wordpress_62222_lawyer_v1/',
		),
		'skin-7' => array(
			'label'    => esc_html__( 'Modern', 'monstroid2' ),
			'full'     => get_template_directory() . '/assets/demo-content/skin-7/skin-7-full.xml',
			'lite'     => get_template_directory() . '/assets/demo-content/skin-7/skin-7-min.xml',
			'thumb'    => get_template_directory_uri() . '/assets/demo-content/skin-7/skin-7-thumb.png',
			'demo_url' => 'https://ld-wp.template-help.com/wordpress_62222_modern/',
		),
		'skin-8' => array(
			'label'    => esc_html__( 'Loan', 'monstroid2' ),
			'full'     => get_template_directory() . '/assets/demo-content/skin-8/skin-8-full.xml',
			'lite'     => get_template_directory() . '/assets/demo-content/skin-8/skin-8-min.xml',
			'thumb'    => get_template_directory_uri() . '/assets/demo-content/skin-8/skin-8-thumb.png',
			'demo_url' => 'https://ld-wp.template-help.com/wordpress_62222_loan_v1/',
		),
		'skin-9' => array(
			'label'    => esc_html__( 'Resto', 'monstroid2' ),
			'full'     => get_template_directory() . '/assets/demo-content/skin-9/skin-9-full.xml',
			'lite'     => get_template_directory() . '/assets/demo-content/skin-9/skin-9-min.xml',
			'thumb'    => get_template_directory_uri() . '/assets/demo-content/skin-9/skin-9-thumb.png',
			'demo_url' => 'https://ld-wp.template-help.com/wordpress_62222_resto/',
		),
		'skin-10' => array(
			'label'    => esc_html__( 'Weelko', 'monstroid2' ),
			'full'     => get_template_directory() . '/assets/demo-content/skin-10/skin-10-full.xml',
			'lite'     => get_template_directory() . '/assets/demo-content/skin-10/skin-10-min.xml',
			'thumb'    => get_template_directory_uri() . '/assets/demo-content/skin-10/skin-10-thumb.png',
			'demo_url' => 'https://ld-wp.template-help.com/wordpress_62222_weelko/',
		),
		'skin-11' => array(
			'label'    => esc_html__( 'IntraBrand', 'monstroid2' ),
			'full'     => get_template_directory() . '/assets/demo-content/skin-11/skin-11-full.xml',
			'lite'     => get_template_directory() . '/assets/demo-content/skin-11/skin-11-min.xml',
			'thumb'    => get_template_directory_uri() . '/assets/demo-content/skin-11/skin-11-thumb.png',
			'demo_url' => 'https://ld-wp.template-help.com/wordpress_62222_intrabrand/',
		),
		'skin-12' => array(
			'label'    => esc_html__( 'Lingua', 'monstroid2' ),
			'full'     => get_template_directory() . '/assets/demo-content/skin-12/skin-12-full.xml',
			'lite'     => get_template_directory() . '/assets/demo-content/skin-12/skin-12-min.xml',
			'thumb'    => get_template_directory_uri() . '/assets/demo-content/skin-12/skin-12-thumb.png',
			'demo_url' => 'https://ld-wp.template-help.com/wordpress_62222_lingua/',
		),
		'skin-13' => array(
			'label'    => esc_html__( 'MarieJuliette', 'monstroid2' ),
			'full'     => get_template_directory() . '/assets/demo-content/skin-13/skin-13-full.xml',
			'lite'     => get_template_directory() . '/assets/demo-content/skin-13/skin-13-min.xml',
			'thumb'    => get_template_directory_uri() . '/assets/demo-content/skin-13/skin-13-thumb.png',
			'demo_url' => 'https://ld-wp.template-help.com/wordpress_62222_mariejuliette/',
		),
	),
	'import' => array(
		'chunk_size' => 3,
	),
	'export' => array(
		'options' => array(
			'mprm_settings',
			'bp-pages',
			'bp-active-components',
			'mp_timetable_general',
			'woocommerce_default_country',
			'woocommerce_shop_page_id',
			'woocommerce_default_catalog_orderby',
			'shop_catalog_image_size',
			'shop_single_image_size',
			'shop_thumbnail_image_size',
			'woocommerce_cart_page_id',
			'woocommerce_checkout_page_id',
			'woocommerce_terms_page_id',
			'tm_woowishlist_page',
			'tm_woocompare_page',
			'tm_woocompare_enable',
			'tm_woocompare_show_in_catalog',
			'tm_woocompare_show_in_single',
			'tm_woocompare_compare_text',
			'tm_woocompare_remove_text',
			'tm_woocompare_page_btn_text',
			'tm_woocompare_show_in_catalog',
			'cherry_projects_options',
			'cherry_projects_options_default',
			'cherry-team',
			'cherry-team_default',
			'cherry-services',
			'cherry-services_default',
		),
		'tables' => array(
			'mp_timetable_data',
		),
	),
);
